{
  "189374":{
    "priorityLevel":"HighPriority",
    "status":"Live",
    "section":"Anesthesiologist",
    "userType":"GroupPrivatePractice",
    "datePosted":"2015-12-16T14:55:42Z",
    "lastUpdate":"2015-12-16T14:55:42Z",
    "questionCategoryOrder":["Facility Information","Job Information and Duties","Job Requirements","Salary and Income Information","Anesthesia Group Information","Essential Information"]
    },
    "personalizedToViewerData":{
      "viewed":false,
      "flagged":false,
      "inquired":false
    },
    "content":{
      "name":["Facility Name","Missouri Baptist Hospital",1.1,"OpenTextField","Text"],
      "street":["Facility Street","3015 N Ballas Rd St Louis, MO 63131",1.2,"OpenTextField","Text"],
      "city":["Facility City","St. Louis",1.3,"OpenTextField","Text"],
      "state":["Facility State","Missouri",1.4,"OpenTextField","Text"],
      "zipCode":["Facility Zip Code","63131",1.5,"OpenTextField","Text"],
      "country":["Facility Country","United States",1.6,"OpenTextField","Text"],
      "website":["Facility Website or Video Link","http://www.missouribaptist.org/",1.7,"OpenTextField","Text"],
      "duration":["Duration of position","Full Time",1.8,"OpenTextField","Text"],
      "minIncome":["Minimum Income","$300,000",1.9,"OpenTextField","Text"],
      "maxIncome":["Maximum Income","$380,000",1.10,"OpenTextField","Text"],
      "briefDescription":["Brief Description","There are 3 possible opportunities.  Partnership track with call, employee tract with call and possibly a surgery center position M-F.",1.11,"OpenTextField","Text"],
      "fullDescription":["Full Description","There are 3 opportunities available.\\n1. A  partnership tract. Most of the work is at Missouri Baptist Hospital.  General practice anesthesia mostly supervising 2-4 CRNAs.  Orthopedics with regional blocks, (Ultrasound skills encouraged).  Vascular, general surgery, neurosurgery, GI lab, and uncomplicated pediatrics. 1st call from home about 2-3 times per month with day off afterwards.  MD can take \"extra\"; call for increased reimbursement.\\n2. The same as above but MD is not on a partnership track and receives increased salary  instead of a graduated \"buy-in\";.\\n3. With the proper candidate, we could consider a surgery center position, Mon - Friday without call.  This would not be a partnership track, but a well compensated employee position.  Knowledge of regional blocks for orthopedics with and \"without\"; ultrasound is mandatory.",1.12,"OpenTextField","Text"],
      "w2or1099":["Employment Status,W-2 (Employee) or 1099 (Independent Contractor)","1099",1.13,"OpenTextField","Text"],
      "startDate":["Start Date","Immediate",1.14,"OpenTextField","Text"],
      "definiteOrPendingJob":["Definite Job or a Pending Job","Definite Job",1.15,"OpenTextField","Text"],
      "firstCallRegularity":["How often will Anesthesiologist be on FIRST call?","Every TENTH night FIRST call",1.16,"OpenTextField","Text"],
      "firstCallOff":["Day off after FIRST call?","Always",1.17,"OpenTextField","Text"],
      "secondCall":["How often will Anesthesiologist be on SECOND call?","Every TENTH night SECOND call",1.18,"OpenTextField","Text"],
      "typeOfWork":["How often the Anesthesiologist \\n will be doing each of the following","Chronic Pain Management : Never\\n Cardiac Anesthesia : Never\\n Thoracic Anesthesia : Never\\n Major Vascular Anesthesia : Sometimes\\n Obstetric Anesthesia : Negotiable\\n Pediatric Anesthesia : Sometimes\\n Neuroanesthesia : Usually\\n Trauma Anesthesia : Never\\n Critical Care Medicine : Never\\n Anesthesia for outpatient surgery : Usually\\n Office based Anesthesia : Never\\n Administrative Leadership Duties : Sometimes\\n Regional Anesthesia : Usually\\n Preop Screening Clinic : Never\\n Orthopedic Anesthesia : Usually\\n Acute Pain Service : Usually",1.19,"OpenTextField","Text"],
      "directingCRNA":["Will anesthesiologist be Medically Directing CRNAs or AAs?","Usually",1.20,"OpenTextField","Text"],
      "percentageDoingCases":["What percentage of the time will anesthesiologist be personally providing anesthesia care?","10% doing own cases",1.21,"OpenTextField","Text"],
      "numeberOfApplicants":["Number of Anesthesiologists needed","1 or 2",2.1,"OpenTextField","Text"],
      "directorPosition":["Is this a Director of Department position?","No",2.2,"OpenTextField","Text"],
      "partnership":["Does this job lead to partnership?","Negotiable",2.3,"OpenTextField","Text"],
      "numberOfWorkmates":["Number of Full-time anesthesiologists","16",2.4,"OpenTextField","Text"],
      "NumOfCRNAFullTime":["Number of Full-time CRNAs","60",2.5,"OpenTextField","Text"],
      "NumOfCRNAPartTime":["Number of Part-time CRNAs","5",2.6,"OpenTextField","Text"],
      "NumOfTecs":["Number of Anesthesia technicians","5",2.7,"OpenTextField","Text"],
      "directedCRNA":["How often are CRNAs performing Operative Cases under medical direction of an anesthesiologist (as opposed to not medically directed)?","Usually",2.8,"OpenTextField","Text"],
      "epiduralDirectedCRNA":["How often are CRNAs performing Labor Epidurals under medical direction of an anesthesiologist (as opposed to not medically directed)?","Usually",2.9,"OpenTextField","Text"],
      "fellowshipRequired":["Subspecialty Fellowship Required?","Negotiable",3.1,"OpenTextField","Text"],
      "expertiseRequired":["Subspecialty Expertise (but not Fellowship) Required?","Negotiable",3.2,"OpenTextField","Text"],
      "requiredLicense":["State License Required","Missouri",3.3,"OpenTextField","Text"],
      "RequiredCertABA":["ABA Certification Status Required","Candidate in ABA exam system",3.4,"OpenTextField","Text"],
      "reCertABA":["ABA Re-certification required every ten years","Negotiable",3.5,"OpenTextField","Text"],
      "underservedArea":["Job located in Medically Underserved Area (MUA)","No",3.6,"OpenTextField","Text"],
      "newGraduatesAccepted":["New Graduates Acceptable?","Yes",3.7,"OpenTextField","Text"],
      "signOnBonus":["Amount of Sign-on Bonus","None",4.1,"OpenTextField","Text"],
      "signOnBonusCommitment":["Sign-on Bonus commitment","None",4.2,"OpenTextField","Text"],
      "malpracticePaid":["Malpractice Paid?","Yes",4.3,"OpenTextField","Text"],
      "malpracticeCoverage":["Amount of Malpractice Coverage?","1million/3million",4.4,"OpenTextField","Text"],
      "salaryIncome":["Does this job provide Salary Income?","Negotiable",4.5,"OpenTextField","Text"],
      "percentageIncome":["Does this job provide Percentage Income?","Negotiable",4.6,"OpenTextField","Text"],
      "fullPartner":["Does this job provide Income as a Full Partner in a group practice?","Negotiable",4.7,"OpenTextField","Text"],
      "feeForService":["Does this job provide Income from Fee-for-service individual practice?","Negotiable",4.8,"OpenTextField","Text"],
      "hospitalEmployee":["Does this job provide Salary from Hospital as an employee?","No",4.9,"OpenTextField","Text"],
      "otherIncome":["Does this job provide Other Income from Hospital as an employee?","No",4.10,"OpenTextField","Text"],
      "educationalLeave":["Weeks Paid Educational Leave","Negotiable",4.11,"OpenTextField","Text"],
      "paidVacation":["Weeks Paid Vacation","8 Weeks",4.12,"OpenTextField","Text"],
      "medicalInsurace":["Medical Insurance Paid","yes",4.13,"OpenTextField","Text"],
      "disabilityInsurace":["Disability Insurance Paid","negotiable",4.14,"OpenTextField","Text"],
      "retirementPlan":["Retirement Plan Paid","yes",4.15,"OpenTextField","Text"],
      "groupName":["Anesthesia Group Name","Ballas Anesthesia Inc.",5.1,"OpenTextField","Text"],
      "groupWebsite":["Anesthesia Group Web Site","http://www.ballasanesthesia.com/",5.2,"OpenTextField","Text"],
      "exclusiveContract":["Does Anesthesia Group have an exclusive contract?","Yes",5.3,"OpenTextField","Text"],
      "groupPresident":["Name of Anesthesiologist who is Group President and years with group","Jeffery Carter  MD",5.1,"OpenTextField","Text"],
      "chiefCRNA":["Name of Chief CRNA","Dan Prost CRNA",5.2,"OpenTextField","Text"],
      "multiHosptialGroup":["Is practice limited to one hospital or involves several hospitals?","One Hospital",5.3,"OpenTextField","Text"],
      "surgeryCenter":["Practice involves a Surgery Center","Negotiable",5.4,"OpenTextField","Text"],
      "officeBased":["Practice involves Office Based Anesthesia?","No",5.5,"OpenTextField","Text"],
      "otherLocations":["Practice involves some other location as described?","Occasional staffing of surgery centers",5.6,"OpenTextField","Text"],
      "residencyProgram":["Is there an Approved Physician residency program?","No",5.7,"OpenTextField","Text"],
      "anesthesiaTraining":["Is there Anesthesia training for Physician house staff?","No",5.8,"OpenTextField","Text"],
      "trainingProgramCRNA":["Is there a CRNA training program?","No",5.9,"OpenTextField","Text"],
      "cityPopulation":["City Population","1 million-2 million",5.10,"OpenTextField","Text"],
      "numOfSurgicalCases":["Number of surgical cases per year","5,001-10,000",5.11,"OpenTextField","Text"],
      "governmentJob":["Federal Government job","No",5.12,"OpenTextField","Text"],
      "companyName":["Company Name","Ballas Anesthesia Inc.",6.1,"OpenTextField","Text"],
      "contactName":["Contact Name","Jeffery Carter MD",6.2,"OpenTextField","Text"],
      "contactEmail":["Contact Email","jeffreydcarter@mac.com",6.3,"OpenTextField","Text"],
      "contactState":["Contact State","Missouri",6.4,"OpenTextField","Text"],
      "contactZip":["Contact Zip Code","63131",6.5,"OpenTextField","Text"],
      "contactCountry":["Contact Country","United States",6.6,"OpenTextField","Text"],
      "contactPhone":["Contact Voice Phone","314-996-5330",6.7,"OpenTextField","Text"],
      "concatMethod":["Preferred Contact Method","No Preference",6.8,"OpenTextField","Text"]
   
  }
}